### ISSUE TITLE
error in conditions() with parsing temp?

### ISSUE THREAD

**Issue by RMHogervorst** [ALShum/rwunderground#12]
```
In data.frame(weather = cond$weather, temp = as.numeric(cond[[paste0("temp_",  :
  NAs introduced by coercion
```
I gues the NA's are not correclty parsed?

however: when I do a raw request 
```
conditions <- rwunderground::conditions(location = "pws:ILEIDEN46", use_metric = TRUE, raw = TRUE)
as.numeric(conditions$current_observation$temp_c)  # does work. 

conditions$current_observation[[temp_c]]  does not work. 
```

**Comment by erichare** [comment]
That second line in your example isn't valid R code, unless temp_c is an object. Note that both these work:

conditions$current_observation$temp_c
conditions$current_observation[["temp_c"]]

No need to convert to numeric as it already is numeric
