### ISSUE TITLE
Why cant I have WebCam urls for a specific date ? 

### ISSUE THREAD

**Issue by AkshayKapila** [ALShum/rwunderground#13]
Can i have webcam urls for specific Location for a specific date ?

**Comment by erichare** [comment]
That would need to be implemented by the backend API itself. As it stands now, we are simply parsing the response from the API, which is documented here: https://www.wunderground.com/weather/api/d/docs?d=data/webcams This just returns a list of nearby webcams for a specific location, but not a specific date - They aren't storing all the images.
