### ISSUE TITLE
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :    arguments imply differing number of rows: 1, 0

### ISSUE THREAD

**Issue by LABurns** [ALShum/rwunderground#21]
When trying to obtain historic weather data from personal/private weather stations using history_range() and set_location(PWS_id =" ") this error is returned. 

Example: 
history_range(set_location(PWS_id = "KORPORTL775"), date_start = "20170520", date_end = "20170521")

**Comment by erichare** [comment]
It seems like that particular PWS id isnt returning any history for that range... the error message admittedly should be better, and we'll work on that, but note that (for instance) this call works fine:

history_range(set_location(city = "Honolulu", territory = "Hawaii"), date_start = "20170520", date_end = "20170521")

Thanks for the report - ill open a separate issue for the ugly error message
