### ISSUE TITLE
Time zones in hourly10day

### ISSUE THREAD

**Issue by krlmlr** [ALShum/rwunderground#24]
The time is derived from the epoch with an origin at 1970-01-01 *in the current time zone*. This means that passing a `tz` argument applies the time zone offset twice, which leads to wrong timestamps.

**Comment by krlmlr** [comment]
Other endpoints are also affected. Okay to pull in lubridate as a dependency?

Obligatory: https://xkcd.com/1883/

**Comment by krlmlr** [comment]
Maybe it's also just a time zone parsing error: The third example is wrong, most likely because `"CEST"` is not recognized.

``` r
as.POSIXct(1504213200, origin = as.POSIXct("1970-01-01", tz = "UTC"))
#> [1] "2017-08-31 23:00:00 CEST"
as.POSIXct(1504213200, origin = as.POSIXct("1970-01-01", tz = "UTC"), tz = "UTC")
#> [1] "2017-08-31 21:00:00 UTC"
as.POSIXct(1504213200, origin = as.POSIXct("1970-01-01", tz = "UTC"), tz = "CEST")
#> [1] "2017-08-31 21:00:00 CEST"
as.POSIXct(1504213200, origin = as.POSIXct("1970-01-01", tz = "UTC"), tz = "Europe/Zurich")
#> [1] "2017-08-31 23:00:00 CEST"
```

**Comment by erichare** [comment]
Merged in the fix. Thank you again!
