### ISSUE TITLE
history, history_range fail for location set as pws

### ISSUE THREAD

**Issue by CraigMohn** [ALShum/rwunderground#25]
the calls to history and history range fail, as the following shows:

history(location=set_location(PWS_id="KWASAMMA58"),date="20170101",key=get_api_key()))

The data returned from wunderground don't contain a result for visibility; this causes an empty result, num(0) to go into the list created on line 47-75 of history.R.  This can be fixed by changing the statements of the form:
   vis = as.numeric(x[[paste0("vis", suffix)]]), 
to:
   vis = ifelse(length(x[[paste0("vis", suffix)]])>0, as.numeric(x[[paste0("vis", suffix)]]), NA_real_)

dplyr bind_rows handle numeric NAs well, but chokes on variables that are all num(0)

**Comment by erichare** [comment]
Should be fixed in the latest GitHub commit, thanks to your and jpshanno's fixes. thanks again!
