### ISSUE TITLE
Sporadic error with history_daily()

### ISSUE THREAD

**Issue by pssguy** [ALShum/rwunderground#31]
```
a <-history_daily(location=set_location(lat_long="49.34,-123.04"), date = "20081017", use_metric = TRUE,
+               key = get_api_key(), raw = FALSE, message = TRUE)
[1] "Requesting: http://api.wunderground.com/api/3831f51632e13a0b/history_20081017/q/49.34,-123.04.json"
Error in hist$dailysummary[[1]] : subscript out of bounds
```

If I actually enter the above url, I get the json returned

in history_daily() dates a year either side i.e. date = "20071017" date = "20091017" work fine

**Comment by erichare** [comment]
Thanks for the report! So... this is more of an issue with not error handling well. If you look at the very bottom of the returned JSON, you'll see:

```
		"dailysummary": [
		]
```

So it actually wasn't available. You'll note history() works okay for this request however. I just added a check for this condition, so now the error returned is a bit more elegant:

```
history_daily(location=set_location(lat_long="49.34,-123.04"), date = "20081017", use_metric = TRUE, key = get_api_key(), raw = FALSE, message = TRUE)
[1] "Requesting: http://api.wunderground.com/api/3831f51632e13a0b/history_20081017/q/49.34,-123.04.json"
Error in history_daily(location = set_location(lat_long = "49.34,-123.04"),  : 
  Daily summary for 49.34,-123.04 does not exist.
```

**Comment by pssguy** [comment]
Thanks for explanation and change.
 I put the function within a tryCatch() wrapper . Got 8 of 10 returns I was after in my code so may be a common problem
