### ISSUE TITLE
daylight saving time

### ISSUE THREAD

**Issue by CraigMohn** [ALShum/rwunderground#32]
The following example shows a problem with the way the text value of time returned from wunderground is processed in the hour when daylight saving time ends.  Recall that time advances from 01:59:59 daylight time to 01:00:00 standard time, at least in Seattle.  Passing the time 01:53:00 to as.POSIXct() is could refer to two separate instants  an hour apart, and apparently yields the second such instant to occur (01:53 standard time).  

df <- rwunderground::history_range(location="KBFI",date_start="20091101",
                                   date_end="20091101",key=get_api_key())
head(df$date)
[1] "2009-11-01 00:53:00 PDT" "2009-11-01 01:00:00 PDT" "2009-11-01 01:26:00 PST" "2009-11-01 01:53:00 PST"
[5] "2009-11-01 01:53:00 PST" "2009-11-01 02:53:00 PST"

The 3rd and 4th results should have been PDT not PST.

It appears that wunderground returns results in chronological order, as the following screenshot of the web result with METARS data included shows:
![kbfi 20091101 metar](https://user-images.githubusercontent.com/28156233/32399921-813f980e-c0b7-11e7-896e-c7bc30a1495d.PNG)

I haven't looked down a level to see if the calls to wunderground return the METARS data with UTC times, but as long as there as the times are assumed to be increasing in real (UTC) terms, it would be easy to determine when the switch from daylight to standard occurs based on the one  nonincreasing timestamp we expect.  If there are zero or two, decisions need to be made.  

It occurs to me that the details of which (PDT/PDT in this example) timezone is chosen may be windows-dependent, since timezone functions rely heavily on the operating system, IIRC.  I have no convenient way to test on a non-windows platform.  However, the problem exists on all systems, since location and local time is not an unambiguous specification of an instant in time during this one hour each year.

**Comment by CraigMohn** [comment]
This is complicated by the fact that on my windows machine, using 2009 and 2016 for  tz="America/Los Angeles", the transition in the result returned by lubridate::dst() changes at a different number of minutes and seconds after the hour depending on year.  Not strictly speaking a bug, since the the correct result is indeterminate.  But it is inconvenient......

**Comment by CraigMohn** [comment]
Testing a fix that should do the job except on those few places where Daylight Saving Time transitions happen at times which are not on the hour, which appears to be limited to some parts of New Zealand and Easter Island.

**Comment by erichare** [comment]
Thank you for the report and for the fix! It's merged in... From my testing your fix works great, but I haven't tested particular edge cases... I'll go ahead and close the issue but if there are specific areas that still need work feel free to reopen more issues.
