### ISSUE TITLE
Error on forecast10day function

### ISSUE THREAD

**Issue by ChristinaHolmes** [ALShum/rwunderground#38]
Receiving this error when using the function:

Error: 'as_tibble' is not an exported object from 'namespace:dplyr'

Passing raw=TRUE removes the error but returns a file type that is not nicely parsed.

**Comment by erichare** [comment]
Thank you! Fixed in the latest commit... switched the dependency to tibble explicitly rather than dplyr.

**Comment by ChristinaHolmes** [comment]
Thank you for the quick fix!
