### ISSUE TITLE
countrycode dependency breakage

### ISSUE THREAD

**Issue by vincentarelbundock** [ALShum/rwunderground#39]
Hi,

I am the maintainer of the `countrycode` package which you use as a dependency.

We're moving to version 1.00.0, and changing the name of the object where regexes and country codes are stored. Before, you had to look into the ``countrycode`` data.frame. Now it's called ``codelist``.

You'll probably want to add a line to check package version before digging right into that object.

This change is permanent; you can rest assured that countrycode will be a reliable dependency into the future.

Sorry for the trouble.

http://github.com/vincentarelbundock/countrycode

**Comment by vincentarelbundock** [comment]
BTW, I recommend you keep loading regexes from my package directly instead of forking it, because we keep making improvements to the regexes. We also have a thorough test suite, etc.

**Comment by erichare** [comment]
Thanks! I've updated the object name.

**Comment by vincentarelbundock** [comment]
@erichare Great. But if I were you, I'd wrap this in a version check. CRAN still hasn't processed the new version, and some of your users may not install it for a while.

Something like:

```
if (packageVersion('countrycode') > '0.19') {
    country_data <- countrycode::codelist[, c("country.name.en", "iso2c", "region")]
} else {
    country_data <- countrycode::countrycode_data[, c("country.name.en", "iso2c", "region")]
}
```

**Comment by erichare** [comment]
Ahh... my mistake! I thought it was already on CRAN.. I just added the version check as you suggested. thanks again.
