### ISSUE TITLE
What is the plan for the no_api option in history_range?

### ISSUE THREAD

**Issue by bbrewington** [ALShum/rwunderground#41]
Here is how it looks currently:

https://github.com/ALShum/rwunderground/blob/54b504b65e786aef2523896e17ad390b16ad21d2/R/history.R#L263-L265

**Comment by erichare** [comment]
Sorry about the delay in this - I haven't personally had much time to work on this lately and may not for  awhile. But if you have any suggestions or would be willing to submit a pull request for a possibly solution, I'd be happy to look into it. I think initially this option was envisioned to use a pre-provided API key, but that was before the package got more popular. I'm not sure of the best approach at this point..

**Comment by ALShum** [comment]
Originally weather underground would expose some weather data as CSV through some non-API URLs.  This flag was intended to grab data using those URLs.  Unfortunately, as of about 6-7 months ago they shut down this source of data and only allow grabbing data through their API
