### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by Tolsi** [ALShum/rwunderground#42]
```
install.packages("devtools")
library(devtools)
install_github("ALShum/rwunderground")
rwunderground::set_api_key("...")
print(history(set_location(territory = "California", city = "San Francisco"), 20060405))
```
and I just got NULL.

What can I do wrong here?

Please add a test notebook with an example of work with the library, and not a pdf with a description of all the functions with which it is unclear how to work.

**Comment by erichare** [comment]
You have not loaded the rwunderground package. The history function you are calling, therefore, is exported from some other package, likely utils. Load rwunderground prior to calling history or explicitly reference with :: as you did on the previous function.

As for the test notebook, maintaining this package is no one's full time (or part time) job. It's a great idea, but in the meantime, the github readme documents the majority of the functionality, as does the help system in R. Please feel free if, as in the process of working with the package, you want to create a vignette / notebook illustrating its functionality, to open a pull request and I'd be happy to look it over and merge it in.
