### ISSUE TITLE
Error in history_daily label:bug

### ISSUE THREAD

**Issue by ChristinaHolmes** [ALShum/rwunderground#43]
Receiving this error message when running history_daily for a location with Precipitation value returned.

Warning message:
In do.call(paste0("as.", class), list(val)) : NAs introduced by coercion

Example: Postal Code = 60666, Date = 4-24-2018

Sample r:

API <-'XXXXX'
Location <- '60666'
rwunderground::set_api_key(API)
location <-rwunderground::set_location(zip_code = Location)
Date = '20180424'
h<-rwunderground::history_daily(location, Date,key=rwunderground::get_api_key(), message = FALSE)

Thanks!

**Comment by erichare** [comment]
Thanks christina! I can reproduce... will investigate and follow up soon

**Comment by erichare** [comment]
Christina,

This seems like a data issue on the part of wunderground - Try a different location, such as 50014, and you'll see that the same call works. Normally, precip is reported in terms of inches (for precipi) or millimeters (for precipm), but for some odd reason its being reported as "T" in your call - hence the failure to parse a numeric value and the return of NA.

I suspect "T" means a trace of precipitation - Perhaps the best way to handle that is to just return 0, or to round up to 0.01... but I think in the absence of a clear solution I'm continue to just let it return NA for now - In your own use of the package, feel free to replace these accordingly.

**Comment by ChristinaHolmes** [comment]
Thank you for the quick response - we will handle appropriately on our end.
