### ISSUE TITLE
get around API limit calls for history

### ISSUE THREAD

**Issue by ALShum** [ALShum/rwunderground#9]
Get around API limit calls by using non-API URLs

**Comment by andypicke** [comment]
Any progress on this? Until about a month or 2 ago, you could simply go to a non-API URL and get a csv file with a year's worth of daily historical data for an airport station. But that doesn't work now; I think maybe they now require an API key? And it seems like you can only get 1 day of historical data w/ API request, so getting a years worth of data uses 365 of your daily 500 API calls...

**Comment by jpshanno** [comment]
I had submitted a pull request with a solution, but there was an error in the fix so I closed it. It seems like there is a 'public' key that wunderground uses to get the data when you look at a single day's data.

I'm fixing the error now, but I'm not sure how Weather Underground will view bypassing their API using this public key. I think it would violate the TOS for API usage, but a bigger problem is that it would be really easy for them to change that key regularly and block this workaround.

**Comment by erichare** [comment]
Yeah... I'm hesitant to devote too much effort to getting around an API limit. It's a shame the limit is so low but any efforts to get around it should come outside the scope of this package as much as possible, especially now that it's available on CRAN and has some active users. 

I'm going to go ahead and close this for now... but if anyone has a solution that doesn't violate the TOS feel free to submit a pull request or open a new issue.
